print('Enter any word or number ;)')
n = input()
print(n)
print('line 1:', n[2])
print('line 2:', n[-1])
print('line 3:', n[:5])
print('line 4:', n[:-2])
print('line 5:', n[::2])
print('line 6:', n[1::2])
print('line 7:', n[::-1])
print('line 8:', n[::-2])
print('line 9:', len(n))
